//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class hierarchia
    {
        [Key]
        public int id { get; set; }
        [RegularExpression("^[a-zA-Z0-9]{1,50}$")]
        public string nazov { get; set; }
        [Required]
        public int patriDo { get; set; }
        [Required]
        [Range(1, 4)]
        public int uroven { get; set; }
        public Nullable<int> veduci { get; set; }

        public virtual zamestnanci zamestnanci { get; set; }
    }
}
